// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbftprotocol.proto

package ucsc.gbft.comm;

public interface ConfirmReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gbftprotocol.ConfirmReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 confirm = 1;</code>
   */
  int getConfirm();
}
