// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbftprotocol.proto

package ucsc.gbft.comm;

/**
 * Protobuf type {@code gbftprotocol.ConfirmReply}
 */
public  final class ConfirmReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gbftprotocol.ConfirmReply)
    ConfirmReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConfirmReply.newBuilder() to construct.
  private ConfirmReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConfirmReply() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConfirmReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            confirm_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConfirmReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConfirmReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ucsc.gbft.comm.ConfirmReply.class, ucsc.gbft.comm.ConfirmReply.Builder.class);
  }

  public static final int CONFIRM_FIELD_NUMBER = 1;
  private int confirm_;
  /**
   * <code>int32 confirm = 1;</code>
   */
  public int getConfirm() {
    return confirm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (confirm_ != 0) {
      output.writeInt32(1, confirm_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (confirm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, confirm_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ucsc.gbft.comm.ConfirmReply)) {
      return super.equals(obj);
    }
    ucsc.gbft.comm.ConfirmReply other = (ucsc.gbft.comm.ConfirmReply) obj;

    if (getConfirm()
        != other.getConfirm()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONFIRM_FIELD_NUMBER;
    hash = (53 * hash) + getConfirm();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ucsc.gbft.comm.ConfirmReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ucsc.gbft.comm.ConfirmReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConfirmReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ucsc.gbft.comm.ConfirmReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConfirmReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ucsc.gbft.comm.ConfirmReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConfirmReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ucsc.gbft.comm.ConfirmReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConfirmReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ucsc.gbft.comm.ConfirmReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConfirmReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ucsc.gbft.comm.ConfirmReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ucsc.gbft.comm.ConfirmReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gbftprotocol.ConfirmReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gbftprotocol.ConfirmReply)
      ucsc.gbft.comm.ConfirmReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConfirmReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConfirmReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ucsc.gbft.comm.ConfirmReply.class, ucsc.gbft.comm.ConfirmReply.Builder.class);
    }

    // Construct using ucsc.gbft.comm.ConfirmReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      confirm_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConfirmReply_descriptor;
    }

    @java.lang.Override
    public ucsc.gbft.comm.ConfirmReply getDefaultInstanceForType() {
      return ucsc.gbft.comm.ConfirmReply.getDefaultInstance();
    }

    @java.lang.Override
    public ucsc.gbft.comm.ConfirmReply build() {
      ucsc.gbft.comm.ConfirmReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ucsc.gbft.comm.ConfirmReply buildPartial() {
      ucsc.gbft.comm.ConfirmReply result = new ucsc.gbft.comm.ConfirmReply(this);
      result.confirm_ = confirm_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ucsc.gbft.comm.ConfirmReply) {
        return mergeFrom((ucsc.gbft.comm.ConfirmReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ucsc.gbft.comm.ConfirmReply other) {
      if (other == ucsc.gbft.comm.ConfirmReply.getDefaultInstance()) return this;
      if (other.getConfirm() != 0) {
        setConfirm(other.getConfirm());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ucsc.gbft.comm.ConfirmReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ucsc.gbft.comm.ConfirmReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int confirm_ ;
    /**
     * <code>int32 confirm = 1;</code>
     */
    public int getConfirm() {
      return confirm_;
    }
    /**
     * <code>int32 confirm = 1;</code>
     */
    public Builder setConfirm(int value) {
      
      confirm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 confirm = 1;</code>
     */
    public Builder clearConfirm() {
      
      confirm_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gbftprotocol.ConfirmReply)
  }

  // @@protoc_insertion_point(class_scope:gbftprotocol.ConfirmReply)
  private static final ucsc.gbft.comm.ConfirmReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ucsc.gbft.comm.ConfirmReply();
  }

  public static ucsc.gbft.comm.ConfirmReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfirmReply>
      PARSER = new com.google.protobuf.AbstractParser<ConfirmReply>() {
    @java.lang.Override
    public ConfirmReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConfirmReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConfirmReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfirmReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ucsc.gbft.comm.ConfirmReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

