// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbftprotocol.proto

package ucsc.gbft.comm;

/**
 * Protobuf type {@code gbftprotocol.ConsensusRequest}
 */
public  final class ConsensusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gbftprotocol.ConsensusRequest)
    ConsensusRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConsensusRequest.newBuilder() to construct.
  private ConsensusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConsensusRequest() {
    key_ = "";
    value_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConsensusRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            masterId_ = input.readInt32();
            break;
          }
          case 16: {

            centerId_ = input.readInt32();
            break;
          }
          case 24: {

            viewId_ = input.readInt32();
            break;
          }
          case 32: {

            sequenceId_ = input.readInt32();
            break;
          }
          case 40: {

            consensusStage_ = input.readInt32();
            break;
          }
          case 49: {

            randomId_ = input.readDouble();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            value_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConsensusRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConsensusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ucsc.gbft.comm.ConsensusRequest.class, ucsc.gbft.comm.ConsensusRequest.Builder.class);
  }

  public static final int MASTERID_FIELD_NUMBER = 1;
  private int masterId_;
  /**
   * <code>int32 masterId = 1;</code>
   */
  public int getMasterId() {
    return masterId_;
  }

  public static final int CENTERID_FIELD_NUMBER = 2;
  private int centerId_;
  /**
   * <code>int32 centerId = 2;</code>
   */
  public int getCenterId() {
    return centerId_;
  }

  public static final int VIEWID_FIELD_NUMBER = 3;
  private int viewId_;
  /**
   * <code>int32 viewId = 3;</code>
   */
  public int getViewId() {
    return viewId_;
  }

  public static final int SEQUENCEID_FIELD_NUMBER = 4;
  private int sequenceId_;
  /**
   * <code>int32 sequenceId = 4;</code>
   */
  public int getSequenceId() {
    return sequenceId_;
  }

  public static final int CONSENSUSSTAGE_FIELD_NUMBER = 5;
  private int consensusStage_;
  /**
   * <code>int32 consensusStage = 5;</code>
   */
  public int getConsensusStage() {
    return consensusStage_;
  }

  public static final int RANDOMID_FIELD_NUMBER = 6;
  private double randomId_;
  /**
   * <code>double randomId = 6;</code>
   */
  public double getRandomId() {
    return randomId_;
  }

  public static final int KEY_FIELD_NUMBER = 7;
  private volatile java.lang.Object key_;
  /**
   * <code>string key = 7;</code>
   */
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 7;</code>
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 8;
  private volatile java.lang.Object value_;
  /**
   * <code>string value = 8;</code>
   */
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <code>string value = 8;</code>
   */
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (masterId_ != 0) {
      output.writeInt32(1, masterId_);
    }
    if (centerId_ != 0) {
      output.writeInt32(2, centerId_);
    }
    if (viewId_ != 0) {
      output.writeInt32(3, viewId_);
    }
    if (sequenceId_ != 0) {
      output.writeInt32(4, sequenceId_);
    }
    if (consensusStage_ != 0) {
      output.writeInt32(5, consensusStage_);
    }
    if (randomId_ != 0D) {
      output.writeDouble(6, randomId_);
    }
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, key_);
    }
    if (!getValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, value_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (masterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, masterId_);
    }
    if (centerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, centerId_);
    }
    if (viewId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, viewId_);
    }
    if (sequenceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, sequenceId_);
    }
    if (consensusStage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, consensusStage_);
    }
    if (randomId_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, randomId_);
    }
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, key_);
    }
    if (!getValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ucsc.gbft.comm.ConsensusRequest)) {
      return super.equals(obj);
    }
    ucsc.gbft.comm.ConsensusRequest other = (ucsc.gbft.comm.ConsensusRequest) obj;

    if (getMasterId()
        != other.getMasterId()) return false;
    if (getCenterId()
        != other.getCenterId()) return false;
    if (getViewId()
        != other.getViewId()) return false;
    if (getSequenceId()
        != other.getSequenceId()) return false;
    if (getConsensusStage()
        != other.getConsensusStage()) return false;
    if (java.lang.Double.doubleToLongBits(getRandomId())
        != java.lang.Double.doubleToLongBits(
            other.getRandomId())) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (!getValue()
        .equals(other.getValue())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MASTERID_FIELD_NUMBER;
    hash = (53 * hash) + getMasterId();
    hash = (37 * hash) + CENTERID_FIELD_NUMBER;
    hash = (53 * hash) + getCenterId();
    hash = (37 * hash) + VIEWID_FIELD_NUMBER;
    hash = (53 * hash) + getViewId();
    hash = (37 * hash) + SEQUENCEID_FIELD_NUMBER;
    hash = (53 * hash) + getSequenceId();
    hash = (37 * hash) + CONSENSUSSTAGE_FIELD_NUMBER;
    hash = (53 * hash) + getConsensusStage();
    hash = (37 * hash) + RANDOMID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRandomId()));
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ucsc.gbft.comm.ConsensusRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ucsc.gbft.comm.ConsensusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ucsc.gbft.comm.ConsensusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gbftprotocol.ConsensusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gbftprotocol.ConsensusRequest)
      ucsc.gbft.comm.ConsensusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConsensusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConsensusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ucsc.gbft.comm.ConsensusRequest.class, ucsc.gbft.comm.ConsensusRequest.Builder.class);
    }

    // Construct using ucsc.gbft.comm.ConsensusRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      masterId_ = 0;

      centerId_ = 0;

      viewId_ = 0;

      sequenceId_ = 0;

      consensusStage_ = 0;

      randomId_ = 0D;

      key_ = "";

      value_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ConsensusRequest_descriptor;
    }

    @java.lang.Override
    public ucsc.gbft.comm.ConsensusRequest getDefaultInstanceForType() {
      return ucsc.gbft.comm.ConsensusRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ucsc.gbft.comm.ConsensusRequest build() {
      ucsc.gbft.comm.ConsensusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ucsc.gbft.comm.ConsensusRequest buildPartial() {
      ucsc.gbft.comm.ConsensusRequest result = new ucsc.gbft.comm.ConsensusRequest(this);
      result.masterId_ = masterId_;
      result.centerId_ = centerId_;
      result.viewId_ = viewId_;
      result.sequenceId_ = sequenceId_;
      result.consensusStage_ = consensusStage_;
      result.randomId_ = randomId_;
      result.key_ = key_;
      result.value_ = value_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ucsc.gbft.comm.ConsensusRequest) {
        return mergeFrom((ucsc.gbft.comm.ConsensusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ucsc.gbft.comm.ConsensusRequest other) {
      if (other == ucsc.gbft.comm.ConsensusRequest.getDefaultInstance()) return this;
      if (other.getMasterId() != 0) {
        setMasterId(other.getMasterId());
      }
      if (other.getCenterId() != 0) {
        setCenterId(other.getCenterId());
      }
      if (other.getViewId() != 0) {
        setViewId(other.getViewId());
      }
      if (other.getSequenceId() != 0) {
        setSequenceId(other.getSequenceId());
      }
      if (other.getConsensusStage() != 0) {
        setConsensusStage(other.getConsensusStage());
      }
      if (other.getRandomId() != 0D) {
        setRandomId(other.getRandomId());
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ucsc.gbft.comm.ConsensusRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ucsc.gbft.comm.ConsensusRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int masterId_ ;
    /**
     * <code>int32 masterId = 1;</code>
     */
    public int getMasterId() {
      return masterId_;
    }
    /**
     * <code>int32 masterId = 1;</code>
     */
    public Builder setMasterId(int value) {
      
      masterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 masterId = 1;</code>
     */
    public Builder clearMasterId() {
      
      masterId_ = 0;
      onChanged();
      return this;
    }

    private int centerId_ ;
    /**
     * <code>int32 centerId = 2;</code>
     */
    public int getCenterId() {
      return centerId_;
    }
    /**
     * <code>int32 centerId = 2;</code>
     */
    public Builder setCenterId(int value) {
      
      centerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 centerId = 2;</code>
     */
    public Builder clearCenterId() {
      
      centerId_ = 0;
      onChanged();
      return this;
    }

    private int viewId_ ;
    /**
     * <code>int32 viewId = 3;</code>
     */
    public int getViewId() {
      return viewId_;
    }
    /**
     * <code>int32 viewId = 3;</code>
     */
    public Builder setViewId(int value) {
      
      viewId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 viewId = 3;</code>
     */
    public Builder clearViewId() {
      
      viewId_ = 0;
      onChanged();
      return this;
    }

    private int sequenceId_ ;
    /**
     * <code>int32 sequenceId = 4;</code>
     */
    public int getSequenceId() {
      return sequenceId_;
    }
    /**
     * <code>int32 sequenceId = 4;</code>
     */
    public Builder setSequenceId(int value) {
      
      sequenceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sequenceId = 4;</code>
     */
    public Builder clearSequenceId() {
      
      sequenceId_ = 0;
      onChanged();
      return this;
    }

    private int consensusStage_ ;
    /**
     * <code>int32 consensusStage = 5;</code>
     */
    public int getConsensusStage() {
      return consensusStage_;
    }
    /**
     * <code>int32 consensusStage = 5;</code>
     */
    public Builder setConsensusStage(int value) {
      
      consensusStage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 consensusStage = 5;</code>
     */
    public Builder clearConsensusStage() {
      
      consensusStage_ = 0;
      onChanged();
      return this;
    }

    private double randomId_ ;
    /**
     * <code>double randomId = 6;</code>
     */
    public double getRandomId() {
      return randomId_;
    }
    /**
     * <code>double randomId = 6;</code>
     */
    public Builder setRandomId(double value) {
      
      randomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double randomId = 6;</code>
     */
    public Builder clearRandomId() {
      
      randomId_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 7;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 7;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 7;</code>
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 7;</code>
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>string key = 7;</code>
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <code>string value = 8;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string value = 8;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string value = 8;</code>
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string value = 8;</code>
     */
    public Builder clearValue() {
      
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <code>string value = 8;</code>
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gbftprotocol.ConsensusRequest)
  }

  // @@protoc_insertion_point(class_scope:gbftprotocol.ConsensusRequest)
  private static final ucsc.gbft.comm.ConsensusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ucsc.gbft.comm.ConsensusRequest();
  }

  public static ucsc.gbft.comm.ConsensusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConsensusRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConsensusRequest>() {
    @java.lang.Override
    public ConsensusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConsensusRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConsensusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConsensusRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ucsc.gbft.comm.ConsensusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

