// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbftprotocol.proto

package ucsc.gbft.comm;

public interface ConsensusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gbftprotocol.ConsensusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 masterId = 1;</code>
   */
  int getMasterId();

  /**
   * <code>int32 centerId = 2;</code>
   */
  int getCenterId();

  /**
   * <code>int32 viewId = 3;</code>
   */
  int getViewId();

  /**
   * <code>int32 sequenceId = 4;</code>
   */
  int getSequenceId();

  /**
   * <code>int32 consensusStage = 5;</code>
   */
  int getConsensusStage();

  /**
   * <code>double randomId = 6;</code>
   */
  double getRandomId();

  /**
   * <code>string key = 7;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 7;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 8;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 8;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
