// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbftprotocol.proto

package ucsc.gbft.comm;

public interface EndRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gbftprotocol.EndRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 centerId = 1;</code>
   */
  int getCenterId();

  /**
   * <code>double randomId = 2;</code>
   */
  double getRandomId();

  /**
   * <code>string key = 3;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 4;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 4;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
