// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbftprotocol.proto

package ucsc.gbft.comm;

public final class GBFTCommProto {
  private GBFTCommProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbftprotocol_ConsensusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbftprotocol_ConsensusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbftprotocol_ViewChangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbftprotocol_ViewChangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbftprotocol_StartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbftprotocol_StartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbftprotocol_EndRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbftprotocol_EndRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbftprotocol_ConfirmReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbftprotocol_ConfirmReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022gbftprotocol.proto\022\014gbftprotocol\"\240\001\n\020C" +
      "onsensusRequest\022\020\n\010masterId\030\001 \001(\005\022\020\n\010cen" +
      "terId\030\002 \001(\005\022\016\n\006viewId\030\003 \001(\005\022\022\n\nsequenceI" +
      "d\030\004 \001(\005\022\026\n\016consensusStage\030\005 \001(\005\022\020\n\010rando" +
      "mId\030\006 \001(\001\022\013\n\003key\030\007 \001(\t\022\r\n\005value\030\010 \001(\t\"Q\n" +
      "\021ViewChangeRequest\022\020\n\010centerId\030\001 \001(\005\022\022\n\n" +
      "nextViewId\030\002 \001(\005\022\026\n\016targetCenterId\030\003 \001(\005" +
      "\"<\n\014StartRequest\022\020\n\010randomId\030\001 \001(\001\022\013\n\003ke" +
      "y\030\002 \001(\t\022\r\n\005value\030\003 \001(\t\"L\n\nEndRequest\022\020\n\010" +
      "centerId\030\001 \001(\005\022\020\n\010randomId\030\002 \001(\001\022\013\n\003key\030" +
      "\003 \001(\t\022\r\n\005value\030\004 \001(\t\"\037\n\014ConfirmReply\022\017\n\007" +
      "confirm\030\001 \001(\0052\272\002\n\tConsensus\022H\n\014startMess" +
      "age\022\032.gbftprotocol.StartRequest\032\032.gbftpr" +
      "otocol.ConfirmReply\"\000\022H\n\016confirmMessage\022" +
      "\030.gbftprotocol.EndRequest\032\032.gbftprotocol" +
      ".ConfirmReply\"\000\022L\n\014claimMessage\022\036.gbftpr" +
      "otocol.ConsensusRequest\032\032.gbftprotocol.C" +
      "onfirmReply\"\000\022K\n\nviewChange\022\037.gbftprotoc" +
      "ol.ViewChangeRequest\032\032.gbftprotocol.Conf" +
      "irmReply\"\000B!\n\016ucsc.gbft.commB\rGBFTCommPr" +
      "otoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gbftprotocol_ConsensusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gbftprotocol_ConsensusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbftprotocol_ConsensusRequest_descriptor,
        new java.lang.String[] { "MasterId", "CenterId", "ViewId", "SequenceId", "ConsensusStage", "RandomId", "Key", "Value", });
    internal_static_gbftprotocol_ViewChangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gbftprotocol_ViewChangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbftprotocol_ViewChangeRequest_descriptor,
        new java.lang.String[] { "CenterId", "NextViewId", "TargetCenterId", });
    internal_static_gbftprotocol_StartRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gbftprotocol_StartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbftprotocol_StartRequest_descriptor,
        new java.lang.String[] { "RandomId", "Key", "Value", });
    internal_static_gbftprotocol_EndRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gbftprotocol_EndRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbftprotocol_EndRequest_descriptor,
        new java.lang.String[] { "CenterId", "RandomId", "Key", "Value", });
    internal_static_gbftprotocol_ConfirmReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gbftprotocol_ConfirmReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbftprotocol_ConfirmReply_descriptor,
        new java.lang.String[] { "Confirm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
