// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbftprotocol.proto

package ucsc.gbft.comm;

public interface StartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gbftprotocol.StartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double randomId = 1;</code>
   */
  double getRandomId();

  /**
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 3;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 3;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
