// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbftprotocol.proto

package ucsc.gbft.comm;

/**
 * Protobuf type {@code gbftprotocol.ViewChangeRequest}
 */
public  final class ViewChangeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gbftprotocol.ViewChangeRequest)
    ViewChangeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ViewChangeRequest.newBuilder() to construct.
  private ViewChangeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ViewChangeRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ViewChangeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            centerId_ = input.readInt32();
            break;
          }
          case 16: {

            nextViewId_ = input.readInt32();
            break;
          }
          case 24: {

            targetCenterId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ViewChangeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ViewChangeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ucsc.gbft.comm.ViewChangeRequest.class, ucsc.gbft.comm.ViewChangeRequest.Builder.class);
  }

  public static final int CENTERID_FIELD_NUMBER = 1;
  private int centerId_;
  /**
   * <code>int32 centerId = 1;</code>
   */
  public int getCenterId() {
    return centerId_;
  }

  public static final int NEXTVIEWID_FIELD_NUMBER = 2;
  private int nextViewId_;
  /**
   * <code>int32 nextViewId = 2;</code>
   */
  public int getNextViewId() {
    return nextViewId_;
  }

  public static final int TARGETCENTERID_FIELD_NUMBER = 3;
  private int targetCenterId_;
  /**
   * <code>int32 targetCenterId = 3;</code>
   */
  public int getTargetCenterId() {
    return targetCenterId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (centerId_ != 0) {
      output.writeInt32(1, centerId_);
    }
    if (nextViewId_ != 0) {
      output.writeInt32(2, nextViewId_);
    }
    if (targetCenterId_ != 0) {
      output.writeInt32(3, targetCenterId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (centerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, centerId_);
    }
    if (nextViewId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, nextViewId_);
    }
    if (targetCenterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, targetCenterId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ucsc.gbft.comm.ViewChangeRequest)) {
      return super.equals(obj);
    }
    ucsc.gbft.comm.ViewChangeRequest other = (ucsc.gbft.comm.ViewChangeRequest) obj;

    if (getCenterId()
        != other.getCenterId()) return false;
    if (getNextViewId()
        != other.getNextViewId()) return false;
    if (getTargetCenterId()
        != other.getTargetCenterId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CENTERID_FIELD_NUMBER;
    hash = (53 * hash) + getCenterId();
    hash = (37 * hash) + NEXTVIEWID_FIELD_NUMBER;
    hash = (53 * hash) + getNextViewId();
    hash = (37 * hash) + TARGETCENTERID_FIELD_NUMBER;
    hash = (53 * hash) + getTargetCenterId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ucsc.gbft.comm.ViewChangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ucsc.gbft.comm.ViewChangeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gbftprotocol.ViewChangeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gbftprotocol.ViewChangeRequest)
      ucsc.gbft.comm.ViewChangeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ViewChangeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ViewChangeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ucsc.gbft.comm.ViewChangeRequest.class, ucsc.gbft.comm.ViewChangeRequest.Builder.class);
    }

    // Construct using ucsc.gbft.comm.ViewChangeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      centerId_ = 0;

      nextViewId_ = 0;

      targetCenterId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ucsc.gbft.comm.GBFTCommProto.internal_static_gbftprotocol_ViewChangeRequest_descriptor;
    }

    @java.lang.Override
    public ucsc.gbft.comm.ViewChangeRequest getDefaultInstanceForType() {
      return ucsc.gbft.comm.ViewChangeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ucsc.gbft.comm.ViewChangeRequest build() {
      ucsc.gbft.comm.ViewChangeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ucsc.gbft.comm.ViewChangeRequest buildPartial() {
      ucsc.gbft.comm.ViewChangeRequest result = new ucsc.gbft.comm.ViewChangeRequest(this);
      result.centerId_ = centerId_;
      result.nextViewId_ = nextViewId_;
      result.targetCenterId_ = targetCenterId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ucsc.gbft.comm.ViewChangeRequest) {
        return mergeFrom((ucsc.gbft.comm.ViewChangeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ucsc.gbft.comm.ViewChangeRequest other) {
      if (other == ucsc.gbft.comm.ViewChangeRequest.getDefaultInstance()) return this;
      if (other.getCenterId() != 0) {
        setCenterId(other.getCenterId());
      }
      if (other.getNextViewId() != 0) {
        setNextViewId(other.getNextViewId());
      }
      if (other.getTargetCenterId() != 0) {
        setTargetCenterId(other.getTargetCenterId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ucsc.gbft.comm.ViewChangeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ucsc.gbft.comm.ViewChangeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int centerId_ ;
    /**
     * <code>int32 centerId = 1;</code>
     */
    public int getCenterId() {
      return centerId_;
    }
    /**
     * <code>int32 centerId = 1;</code>
     */
    public Builder setCenterId(int value) {
      
      centerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 centerId = 1;</code>
     */
    public Builder clearCenterId() {
      
      centerId_ = 0;
      onChanged();
      return this;
    }

    private int nextViewId_ ;
    /**
     * <code>int32 nextViewId = 2;</code>
     */
    public int getNextViewId() {
      return nextViewId_;
    }
    /**
     * <code>int32 nextViewId = 2;</code>
     */
    public Builder setNextViewId(int value) {
      
      nextViewId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nextViewId = 2;</code>
     */
    public Builder clearNextViewId() {
      
      nextViewId_ = 0;
      onChanged();
      return this;
    }

    private int targetCenterId_ ;
    /**
     * <code>int32 targetCenterId = 3;</code>
     */
    public int getTargetCenterId() {
      return targetCenterId_;
    }
    /**
     * <code>int32 targetCenterId = 3;</code>
     */
    public Builder setTargetCenterId(int value) {
      
      targetCenterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 targetCenterId = 3;</code>
     */
    public Builder clearTargetCenterId() {
      
      targetCenterId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gbftprotocol.ViewChangeRequest)
  }

  // @@protoc_insertion_point(class_scope:gbftprotocol.ViewChangeRequest)
  private static final ucsc.gbft.comm.ViewChangeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ucsc.gbft.comm.ViewChangeRequest();
  }

  public static ucsc.gbft.comm.ViewChangeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ViewChangeRequest>
      PARSER = new com.google.protobuf.AbstractParser<ViewChangeRequest>() {
    @java.lang.Override
    public ViewChangeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ViewChangeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ViewChangeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ViewChangeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ucsc.gbft.comm.ViewChangeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

