// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbftprotocol.proto

package ucsc.gbft.comm;

public interface ViewChangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gbftprotocol.ViewChangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 centerId = 1;</code>
   */
  int getCenterId();

  /**
   * <code>int32 nextViewId = 2;</code>
   */
  int getNextViewId();

  /**
   * <code>int32 targetCenterId = 3;</code>
   */
  int getTargetCenterId();
}
